version: '2'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-py3
    volumes:
      - ./workdir:/workdir
    working_dir: /workdir
    ports:
      - 8888:8888
    environment:
      PASSWORD: password
